version: '3'
services:
    db:
        image: postgres
        ports:
          - "5432:5432" 
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: reviews
    api:
        build: .
        command: bash -c "npm start && npm run build:db"
        image: leave-review
        ports:
          - "3000:3000"
        volumes:
          - .:/app
        depends_on:
          - db
        environment:
          DB_HOST: db
          
  # volumes:
  #   pgdata:

# Change port to 80:3000 on API ports
# Remake image