version: '3'
services:
    web:
        image: leave-review
        command: bash -c "npm start && npm run build:db"
        ports:
          - "3000:3000"
        volumes:
          - .:/app
        environment:
          DB_HOST: "13.58.85.48"
          
  # volumes:
  #   pgdata:

# Change port to 80:3000 on API ports
# Remake image